# image:
#   file: .gitpod.Dockerfile

tasks:
  - init: pnpm i
  - init: sudo apt update && sudo apt install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabi qemu qemu-user -y
  - command: docker-compose build
