name: build-windows

on: 
  push:
  pull_request:

jobs:
  build-windows:
    strategy:
      matrix:
        windows: [windows-2019, windows-2022]
      fail-fast: false
    runs-on: ${{ matrix.windows }}
    steps:
      - uses: actions/checkout@v2
      - name: Build and run
        run: |
          cd predefined-macro/
          mkdir ./build
          cd ./build
          cmake ..
          cmake --build .
          Debug/macro_out
      - name: Environment Information
        run: npx envinfo
