name: build-windows

jobs:
  build-windows:
    strategy:
      matrix:
        windows: [windows-2019, windows-2022]
      fail-fast: false
    runs-on: ${{ matrix.windows }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install deps
        run: choco install nasm
      - name: Environment Information
        run: npx envinfo
      - name: Build and run
        run: |
          cd predefined-macro/
          mkdir ./build
          cd ./build
          cmake ..
          cmake --build .
          ./macro_out
